### ISSUE TITLE
Plugin doesn't work with Docker 17.x

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/libnetwork-plugin#154]
calico/node STs have started failing ~with new versions of docker~ on my machine, suggests the plugin is not working (or needs to be installed differently).

## Expected Behavior
`docker network create` should work with calico plugin

## Current Behavior
```
docker exec -it host1 sh -c 'docker network create --driver calico --ipam-driver calico-ipam  testnet1'
  # Return code: 1
  # Error response from daemon: legacy plugin: plugin not found
  # 
```

## Possible Solution
Error message hints that it can't find the plugin or our socket.  Maybe we just need update where we're installed?

## Steps to Reproduce (for bugs)

1. install docker 17.05.0-ce (also repros on 1.12)
2. install plugin as the STs do
3. run above command
4.

## Your Environment

* Docker version: 17.05.0-ce
* Libnetwork-plugin version: v1.1.0 I think
* How you deployed the libnetwork plugin: calico node STs
* Operating System and version: Ubuntu 16.04
* Link to your project (optional):

**Comment by fasaxc** [comment]
Hmm, I tried downgrading my docker but it didn't help and it looks like semaphore have upgraded to 17.03 with no issue so maybe this is a problem with my machine.

**Comment by fasaxc** [comment]
This _does_ work on a freshly-booted Ubutnu 16.04 machine on GCE with docker 1.12.6 (installed with apt-get).  I don't get it :-/

**Comment by tomdee** [comment]
I have a simple repro of this:
```
docker pull docker:dind
make run-plugin
DOCKER_HOST=localhost:5375 docker network create -d calico --ipam-driver=calico tom-test
```

Then I can see the plugin logs using `docker exec dind cat plugin.log`

**Comment by tomdee** [comment]
Ooops, I was seeing `Plugin does not implement the requested driver` but @fasaxc is seeing `plugin not found`.

**Comment by tomdee** [comment]
I can't repro this 👎

**Comment by tmjd** [comment]
@fasaxc do you think this issue should remain open?  Its been a while since you reported it, did you figure anything out that fixed it?

**Comment by fasaxc** [comment]
Nope, haven't figured out what's special about my machine.  Let's close until I work it out.
